### ISSUE TITLE
Send notifications

### ISSUE THREAD

**Issue by GAumala** [cedricblondeau/world-cup-2018-cli-dashboard#28]
Hi, I've been using this tool to "watch" the game at work, and it's great! Thanks for publishing it!

Since I'm a little busy I can't stare at the terminal all morning, so I was wondering  if would be possible to use something like [node-notifier](https://github.com/mikaelbr/node-notifier) to send desktop notifications on important events like goals or bookings. Maybe it could be hidden behind an environment variable like the display emojis feature since probably some people don't want notifications.

I could try sending a pull request if you think this would be useful. I've been looking through the codebase a little to get an idea of how to implement this. I think that currently it just scrapes some website every 30 seconds or so, collects the new data and re renders everything. I guess that I would need to keep a list of past events and generate a new event list before rendering again. If the lists differ then a notification should be posted. What do you think?

**Comment by cedricblondeau** [comment]
Hi Gabriel,

I think that would be an **awesome addition** and I'd love to see a PR adding this feature 🎉👍.

I think I'd definitely use it for goals and I agree it should probably be behind a config/environment variable. So far I was relying on the visual bell in iTerm2 but it does not tell us if there is a goal and in what match.

As you already found, the app is currently polling the _awesome_ worldcup.sfg.io matches API endpoint to update matches.

At this point, the app is not using any state container lib such as Redux and the state is is managed in the root component which is `Dashboard` (`src/components/dashboard.jsx`).

I think it would be reasonable to do something in `updateMatches` before updating the state: https://github.com/cedricblondeau/world-cup-2018-cli-dashboard/blob/master/src/components/Dashboard/Dashboard.jsx#L131.

Alternatively, it could be done on `componentWillUpdate` in `Dashboard`:

```js
class Dashboard extends Component {
  [...]
  componentWillUpdate(nextProps, nextState) {
    // TODO: Check this.state.matches and nextState.matches
  }
  [...]
}
```

That said, I'm wondering if it should really be the responsibility of a component to trigger the notifications 🤔. Also, I think it could be great to isolate the notification responsibility in a separate module such as `src/notifier.js` or something like this so we don't leave too much responsibilities to `Dashboard`.

I think that would not work in a docker container but it seems that `node-notifier` is **not** making it more difficult to ship the dashboard through Docker, so that looks really good. 🎉

**Comment by GAumala** [comment]
Yes I agree that there should be a module "src/notifier.js" to avoid cluttering the dashboard component. 

There's no need to have a state container lib, we only need a module that keeps track of past events in ongoing matches so that at every update the new data can be compared with the previous and return the new events that should go in the notifications. I already have it implemented in #32 check it out.

**Comment by GAumala** [comment]
I sent the PR with the `src/notifier.js` nodule. Currently the notifications just contain the raw event data. There still needs to be a formatting function for better readabilty and UX. I don't think I can use the `format.js` module since that seems to only format text for a terminal. It would also be nice to customize the notifications (add an icon?) with the options available with `node-notifier`.

**Comment by cedricblondeau** [comment]
That's pretty awesome @GAumala 

![neymar-goal-notif](https://user-images.githubusercontent.com/1479924/42171976-b77b6896-7de8-11e8-8519-d5b8d17e20b4.jpg)

I agree it would be great to add some formatting and having icons would even more awesome.

I'm wondering if it would make sense to have another `format.js` dedicated to notifications that would live in a separate folder with `EventTracker` and `notifier`?

```
- api
- components
- notifications
    -- __tests__
    -- EventTracker.js
    -- format.js
    -- notifier.js
```

Any thoughts?

**Comment by GAumala** [comment]
Yes, that sounds great.
