### ISSUE TITLE
"exec format error"

### ISSUE THREAD

**Issue by zhaojjxvi** [cedricblondeau/world-cup-2018-cli-dashboard#38]
Hi there,

Thanks for your dashboard.
When I was trying to run it on my Raspberry Pi 3b, it popped an error like:
`standard_init_linux.go:190: exec user process caused "exec format error"`

Would you please kindly help and check? thank you.

**Comment by cedricblondeau** [comment]
Hi @zhaojjxvi -- Thanks for reporting this. I'd assume that this error comes from Docker 🐳, is it?

It may have to do with the fact that the Raspberry Pi 3b uses an ARM architecture and the current image may not support this.

**Comment by zhaojjxvi** [comment]
Hi @cedricblondeau 

Yes, your assumption is right.
It's a pity that my RPi can't run this awesome dashboard.

But still, thank you for developing and sharing.

**Comment by cedricblondeau** [comment]
Adding multi-arch support for the image should be possible. It would be great to have a PR for this.

In the meantime, I think you can still install it using npm or yarn on a RPi?

**Comment by badukaire** [comment]
I was about to report the same issue. The same version of the image works fine on docker for windows, but not on docker for RPi.

I have read on [stack overflow](https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error) that this may be caused by the fileformat of some files. Shall I give it a try? Which files do you think I should modify?

**Comment by cedricblondeau** [comment]
Note that you can also build the image on the RPi:

```
docker build -t world-cup-2018-cli-dashboard github.com/cedricblondeau/world-cup-2018-cli-dashboard && \
docker run -ti world-cup-2018-cli-dashboard
```

I just tested this on a RPi3 (armv7l) and it worked well. 🎉

Then if we do `docker inspect world-cup-2018-cli-dashboard | grep -i Architecture` we can see:

```
        "Architecture": "arm",
```

While if we pull `cedricbl/world-cup-2018-cli-dashboard | grep -i Architecture`, and we do `docker inspect cedricbl/world-cup-2018-cli-dashboard`, we can see:

```
[...]
        "Architecture": "amd64",
[...]
```

So, the problem is that the image on Docker Hub is for `amd64` only.

**Comment by cedricblondeau** [comment]
I just updated the README with instructions for non `amd64` archs.

https://github.com/cedricblondeau/world-cup-2018-cli-dashboard/blob/e84b909c69e3eff882acae35b45d1d81c8d4a9d4/README.md#L7-L26

**Comment by zhaojjxvi** [comment]
yeah, the way to build and run works well.

Thank you~

**Comment by badukaire** [comment]
Hi Cédric. Just tried and it worked too. Awesome. This issue has been for me a really nice way for learning docker.

Thanks so much.
