### ISSUE TITLE
Where are my flags?

### ISSUE THREAD

**Issue by MarkYSA** [cedricblondeau/world-cup-2018-cli-dashboard#6]
Where are my flags?

![screenshot from 2018-06-21 13-47-56](https://user-images.githubusercontent.com/11468108/41714661-c5230996-7559-11e8-9b67-da334c955897.png)

**Comment by MarkYSA** [comment]
built from docker

**Comment by cedricblondeau** [comment]
Interesting, looks like it cannot render those emojis. What terminal do you use?

**Comment by MarkYSA** [comment]
I'm using GNOME Terminal 3.28.1

**Comment by cedricblondeau** [comment]
I'm wondering if the current terminal configuration can render flag emojis at all. What do you see if you paste 🇧🇷in your terminal?

I think that may be caused by the font configuration also.

If you can live without emojis (I cannot 😄 ) `1.0.0` has been released yesterday and includes a new dashboard giving more information about matches, allows navigation and give the ability to disable emojis.
![screenshot](https://raw.githubusercontent.com/cedricblondeau/world-cup-2018-cli-dashboard/master/screenshot.gif)

To start the dashboard without emojis with docker 🐳:
```
docker pull cedricbl/world-cup-2018-cli-dashboard && docker run -ti -e TZ=America/Toronto -e WITH_EMOJIS=0 cedricbl/world-cup-2018-cli-dashboard
```

I'll keep this open because I'd love to get to the bottom of why some terminals can display them and some cannot at some point.

**Comment by edbizarro** [comment]
Yeah, rxvt-unicode is not showing either.
