### ISSUE TITLE
The border looks uncomfortable

### ISSUE THREAD

**Issue by ZYSzys** [cedricblondeau/world-cup-2018-cli-dashboard#7]
Emmm, Look at the border.It makes me a bit uncomfortable.
Can you solve it~~
![screen shot 2018-06-22 at 11 14 07 pm](https://user-images.githubusercontent.com/23313266/41784367-14cfaaf8-7672-11e8-9222-e58035f9398f.png)

**Comment by cedricblondeau** [comment]
I think this is caused by emojis.

`1.0.` has been released yesterday and includes a new dashboard giving more information about matches, allows navigation and get rid of most borders:
![screenshot](https://raw.githubusercontent.com/cedricblondeau/world-cup-2018-cli-dashboard/master/screenshot.gif)

That said, emojis can still cause other issues and we now have the `WITH_EMOJIS` environment variable to enable or disable them.

To start the dashboard with emojis:
```
WITH_EMOJIS=1 wc2018
```

To start the dashboard without emojis:
```
WITH_EMOJIS=0 wc2018
```
